Log.me().debug('testLogger - this is a test message to platform event 1');
Log.me().pause();
Log.me().debug('testLogger - this is a test message to platform event 2');
Log.me().debug('testLogger - this is a test message to platform event 3');
Log.me().debug('testLogger - this is a test message to platform event 4');
Log.me().debug('testLogger - this is a test message to platform event 5');
Log.me().resume();
Log.me().debug('testLogger - this is a test message to platform event 6');